### ISSUE TITLE
‍🌤💩🈸么网站

### ISSUE THREAD

**Issue by chenxuuu** [otomad/otomad.github.io#1]
https://github.com/otomad/otomad.github.io/blob/f893d158e35d0440515cd92e467a8d09991d47d5/generator/emoji/index.html#L144

**Comment by otomad** [comment]
抱歉，之前我也不知道从网上哪里弄来的抽象话生成器的源码。

已将页面的源码信息更换为你的网站了。

**Comment by chenxuuu** [comment]
没事，随便翻到的，网上一大堆都是😂
